const $=s=>document.querySelector(s);let tab="dashboard",categories=[];
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function boot(){try{const me=await api("/api/me");if(!me.user||me.user.role!=="admin"){location.href="/";return}categories=await api("/api/categories");render()}catch(e){location.href="/"}}
document.querySelectorAll("aside button[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$("#logout").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.href="/"};
async function render(){const titles={dashboard:"Dashboard",products:"Products",categories:"Categories",orders:"Orders",customers:"Customers",settings:"Settings"};$("#title").textContent=titles[tab];if(tab==="dashboard")return dashboard();if(tab==="products")return products();if(tab==="categories")return cats();if(tab==="orders")return orders();if(tab==="customers")return customers();if(tab==="settings")return settings()}
async function dashboard(){const s=await api("/api/admin/stats");$("#content").innerHTML=`<div class="wrap"><div class="cards"><div class="stat">Products<b>${s.products}</b></div><div class="stat">Orders<b>${s.orders}</b></div><div class="stat">Customers<b>${s.customers}</b></div><div class="stat">Sales<b>₹${Number(s.sales).toLocaleString("en-IN")}</b></div></div><div class="table-wrap"><table><tr><th>Low-stock products</th><td>${s.lowStock}</td></tr></table></div></div>`}
async function products(){const ps=await api("/api/admin/products");$("#content").innerHTML=`<div class="wrap"><form id="add" class="form" enctype="multipart/form-data"><input name="name" placeholder="Product name" required><input name="brand" placeholder="Brand"><input name="price" type="number" step="0.01" placeholder="Price" required><input name="discount_price" type="number" step="0.01" placeholder="Discount price"><input name="stock" type="number" placeholder="Stock"><input name="sku" placeholder="SKU"><select name="category_id">${categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select><select name="status"><option value="available">Available</option><option value="out_of_stock">Out of Stock</option><option value="hidden">Hidden</option></select><textarea name="description" placeholder="Description"></textarea><textarea name="specifications" placeholder="Specifications"></textarea><input class="full" name="images" type="file" accept="image/*" multiple><button class="btn full">Upload Product</button></form><div class="table-wrap"><table><tr><th>Image</th><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr>${ps.map(p=>`<tr><td>${p.images[0]?`<img class="thumb" src="${p.images[0]}">`:"—"}</td><td>${esc(p.name)}<br><small>${esc(p.category_name||"")}</small></td><td>₹${p.discount_price??p.price}</td><td>${p.stock}</td><td>${p.status}</td><td><button onclick="editProduct(${p.id})">Edit</button> <button class="danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}</table></div></div>`;$("#add").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin/products",{method:"POST",body:new FormData(e.target)});alert("Product uploaded");render()}catch(err){alert(err.message)}}}
async function editProduct(id){const ps=await api("/api/admin/products");const p=ps.find(x=>x.id===id);if(!p)return;$("#content").innerHTML=`<div class="wrap"><form id="edit" class="form"><input name="name" value="${esc(p.name)}" required><input name="brand" value="${esc(p.brand||"")}"><input name="price" type="number" step="0.01" value="${p.price}"><input name="discount_price" type="number" step="0.01" value="${p.discount_price??""}"><input name="stock" type="number" value="${p.stock}"><input name="sku" value="${esc(p.sku||"")}"><select name="category_id">${categories.map(c=>`<option value="${c.id}" ${c.id===p.category_id?"selected":""}>${esc(c.name)}</option>`).join("")}</select><select name="status">${["available","out_of_stock","hidden"].map(s=>`<option ${p.status===s?"selected":""}>${s}</option>`).join("")}</select><textarea name="description">${esc(p.description||"")}</textarea><textarea name="specifications">${esc(p.specifications||"")}</textarea><button class="btn full">Save changes</button><button type="button" onclick="render()">Cancel</button></form></div>`;$("#edit").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await api("/api/admin/products/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});render()}catch(err){alert(err.message)}}}
async function deleteProduct(id){if(!confirm("Delete this product?"))return;await api("/api/admin/products/"+id,{method:"DELETE"});render()}
async function cats(){categories=await api("/api/categories");$("#content").innerHTML=`<div class="wrap"><form id="cat" class="form"><input name="name" placeholder="New category" required><button class="btn">Add Category</button></form><div class="table-wrap"><table><tr><th>Name</th><th>Action</th></tr>${categories.map(c=>`<tr><td>${esc(c.name)}</td><td><button onclick="renameCat(${c.id},'${esc(c.name)}')">Rename</button> <button class="danger" onclick="deleteCat(${c.id})">Delete</button></td></tr>`).join("")}</table></div></div>`;$("#cat").onsubmit=async e=>{e.preventDefault();await api("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:e.target.name.value})});render()}}
async function renameCat(id,name){const n=prompt("New category name",name);if(n)await api("/api/admin/categories/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n})});render()}
async function deleteCat(id){if(confirm("Delete category?")){await api("/api/admin/categories/"+id,{method:"DELETE"});render()}}
async function orders(){const os=await api("/api/admin/orders");$("#content").innerHTML=`<div class="wrap"><div class="table-wrap"><table><tr><th>Order</th><th>Customer</th><th>Total</th><th>Items</th><th>Status</th></tr>${os.map(o=>`<tr><td>#${o.id}<br><small>${o.created_at}</small></td><td>${esc(o.customer_name)}<br>${esc(o.phone)}<br>${esc(o.address)}, ${esc(o.city)} - ${esc(o.pincode)}</td><td>₹${o.total}</td><td>${o.items.map(i=>`${esc(i.product_name)} × ${i.quantity}`).join("<br>")}</td><td><select onchange="updateOrder(${o.id},this.value)">${["new","processing","shipped","delivered","cancelled"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</table></div></div>`}
async function updateOrder(id,status){await api("/api/admin/orders/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})})}
async function customers(){const cs=await api("/api/admin/customers");$("#content").innerHTML=`<div class="wrap"><div class="table-wrap"><table><tr><th>ID</th><th>Name</th><th>Email</th><th>Joined</th></tr>${cs.map(c=>`<tr><td>${c.id}</td><td>${esc(c.name)}</td><td>${esc(c.email)}</td><td>${c.created_at}</td></tr>`).join("")}</table></div></div>`}
function settings(){$("#content").innerHTML=`<div class="wrap"><form id="pw" class="form"><h3 class="full">Change admin password</h3><input name="currentPassword" type="password" placeholder="Current password" required><input name="newPassword" type="password" placeholder="New password (8+ characters)" required><button class="btn full">Change Password</button></form></div>`;$("#pw").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin/change-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert("Password changed")}catch(err){alert(err.message)}}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
boot();