const $=s=>document.querySelector(s);
let cart=JSON.parse(localStorage.getItem("cart")||"[]"), selectedCategory="";
const money=n=>"₹"+Number(n).toLocaleString("en-IN",{maximumFractionDigits:2});
function saveCart(){localStorage.setItem("cart",JSON.stringify(cart));$("#cartCount").textContent=cart.reduce((a,x)=>a+x.quantity,0)}
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong");return d}
async function loadCategories(){const cs=await api("/api/categories");$("#categories").innerHTML=`<button class="chip active" data-id="">All</button>`+cs.map(c=>`<button class="chip" data-id="${c.id}">${c.name}</button>`).join("");document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.id;document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");loadProducts()})}
async function loadProducts(){const p=new URLSearchParams({q:$("#search").value,category:selectedCategory,min:$("#min").value,max:$("#max").value,brand:$("#brand").value,sort:$("#sort").value});const rows=await api("/api/products?"+p);$("#products").innerHTML=rows.length?rows.map(productCard).join(""):`<div class="muted">No products found.</div>`}
function productCard(p){const price=p.discount_price??p.price;return `<article class="card"><a href="#product/${p.id}"><div class="pic">${p.images[0]?`<img src="${p.images[0]}" alt="">`:`<div class="noimg">🛍️</div>`}</div></a><div class="card-body"><div class="brand">${p.brand||p.category_name||"Product"}</div><h3>${escapeHtml(p.name)}</h3><div class="price">${money(price)} ${p.discount_price?`<span class="old">${money(p.price)}</span>`:""}</div><button class="btn add" onclick="addToCart(${p.id})">Add to Cart</button></div></article>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function addToCart(id){const p=await api("/api/products/"+id);const x=cart.find(i=>i.product_id===id);if(x)x.quantity=Math.min(x.quantity+1,p.stock);else cart.push({product_id:id,name:p.name,price:p.discount_price??p.price,image:p.images[0]||"",quantity:1});saveCart();alert("Added to cart");}
function openModal(html){$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
async function productPage(id){const p=await api("/api/products/"+id);openModal(`<div class="product-detail"><div class="gallery">${(p.images.length?p.images:[""]).map(x=>x?`<img src="${x}" alt="">`:`<div class="pic">🛍️</div>`).join("")}</div><div><div class="brand">${p.brand||p.category_name||""}</div><h2>${escapeHtml(p.name)}</h2><div class="price">${money(p.discount_price??p.price)} ${p.discount_price?`<span class="old">${money(p.price)}</span>`:""}</div><p class="muted">${p.stock>0?"In stock":"Out of stock"}</p><p>${escapeHtml(p.description||"No description.")}</p><h4>Specifications</h4><p>${escapeHtml(p.specifications||"Not provided")}</p><button class="btn" ${p.stock<1?"disabled":""} onclick="addToCart(${p.id})">Add to Cart</button></div></div>`)}
function cartModal(){const total=cart.reduce((a,x)=>a+x.price*x.quantity,0);openModal(`<h2>Your Cart</h2>${cart.length?cart.map((x,i)=>`<div style="display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid #eee"><div style="width:55px;height:55px;background:#f1f2f5;border-radius:8px">${x.image?`<img src="${x.image}" style="width:100%;height:100%;object-fit:cover;border-radius:8px">`:"🛍️"}</div><div style="flex:1"><b>${escapeHtml(x.name)}</b><div>${money(x.price)} × <input style="width:55px;padding:5px" type="number" min="1" value="${x.quantity}" onchange="changeQty(${i},this.value)"></div></div><button onclick="removeCart(${i})">Remove</button></div>`).join("")+`<h3>Total: ${money(total)}</h3><button class="btn" onclick="checkout()">Checkout</button>`:`<p>Your cart is empty.</p>`}`)}
function changeQty(i,v){cart[i].quantity=Math.max(1,Math.min(99,Number(v)||1));saveCart();cartModal()}
function removeCart(i){cart.splice(i,1);saveCart();cartModal()}
async function checkout(){const me=await api("/api/me");if(!me.user)return loginModal("Please login before checkout.");openModal(`<h2>Checkout</h2><form class="form" id="checkout"><input name="customer_name" placeholder="Full name" required><input name="customer_email" type="email" value="${me.user.email}" placeholder="Email" required><input name="phone" placeholder="Phone" required><input name="address" placeholder="Address" required><input name="city" placeholder="City" required><input name="pincode" placeholder="Pincode" required><button class="btn">Place Order</button></form>`);$("#checkout").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e));data.items=cart.map(x=>({product_id:x.product_id,quantity:x.quantity}));try{const r=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});cart=[];saveCart();openModal(`<h2>Order placed 🎉</h2><p>Your order #${r.orderId} has been created.</p>`)}catch(err){alert(err.message)}}}
function loginModal(message=""){openModal(`<h2>Login</h2>${message?`<p class="muted">${message}</p>`:""}<form class="form" id="login"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button class="btn">Login</button></form><p>New customer? <button onclick="registerModal()">Create account</button></p>`);$("#login").onsubmit=async e=>{e.preventDefault();try{await api("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e)))});closeModal();alert("Logged in");}catch(err){alert(err.message)}}}
function registerModal(){openModal(`<h2>Create account</h2><form class="form" id="register"><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="6" placeholder="Password" required><button class="btn">Create Account</button></form>`);$("#register").onsubmit=async e=>{e.preventDefault();try{await api("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e)))});closeModal();alert("Account created");}catch(err){alert(err.message)}}}
async function account(){const me=await api("/api/me");if(!me.user)return loginModal();const orders=await api("/api/orders/my");openModal(`<h2>My Account</h2><p>Welcome, <b>${escapeHtml(me.user.name)}</b></p><button class="btn" onclick="logout()">Logout</button><h3>My Orders</h3>${orders.length?orders.map(o=>`<div style="padding:12px 0;border-bottom:1px solid #eee"><b>#${o.id}</b> — ${o.status} — ${money(o.total)}</div>`).join(""):"<p>No orders yet.</p>"}`)}
async function logout(){await api("/api/auth/logout",{method:"POST"});closeModal();alert("Logged out")}
window.addEventListener("hashchange",()=>{const h=location.hash;if(h.startsWith("#product/"))productPage(h.split("/")[1]);else if(h==="#account")account();});
$("#searchForm").onsubmit=e=>{e.preventDefault();loadProducts();location.hash="#shop"};$("#sort").onchange=loadProducts;$("#apply").onclick=loadProducts;$("#cartBtn").onclick=cartModal;$("#accountLink").onclick=e=>{e.preventDefault();location.hash="#account"};saveCart();loadCategories();loadProducts();